use crate::svd::Device;
use anyhow::Result;

use proc_macro2::{Ident, Span, TokenStream};
use quote::{quote, ToTokens};

use crate::generate::interrupt;
use crate::util::{self, ToSanitizedUpperCase};

use log::info;

pub fn render(d: &Device, device_x: &mut String) -> Result<TokenStream> {
    let mut out = TokenStream::new();

    let doc = format!(
        "Peripheral access API for {0} microcontrollers \
         (generated using svd2mmio-ll-rs v{1})\n\n\
         You can find an overview of the generated API [here].\n\n\
         API features to be included in the [next] svd2mmio-ll-rs \
         release can be generated by cloning the svd2mmio-ll-rs [repository], \
         checking out the above commit, and running `cargo doc --open`.\n\n\
         [here]: https://docs.rs/svd2mmio-ll-rs/{1}/svd2mmio-ll-rs/#peripheral-api\n\
         [next]: https://github.com/no111u3/svd2mmio-ll-rs/blob/master/CHANGELOG.md#unreleased\n\
         [repository]: https://github.com/no111u3/svd2mmio-ll-rs",
        d.name.to_uppercase(),
        env!("CARGO_PKG_VERSION")
    );

    out.extend(quote! {
        #![doc = #doc]
        // Deny a subset of warnings
        #![deny(const_err)]
        #![deny(dead_code)]
        #![deny(improper_ctypes)]
        #![deny(missing_docs)]
        #![deny(no_mangle_generic_items)]
        #![deny(non_shorthand_field_patterns)]
        #![deny(overflowing_literals)]
        #![deny(path_statements)]
        #![deny(patterns_in_fns_without_body)]
        #![deny(private_in_public)]
        #![deny(unconditional_recursion)]
        #![deny(unused_allocation)]
        #![deny(unused_comparisons)]
        #![deny(unused_parens)]
        #![deny(while_true)]
        // Explicitly allow a few warnings that may be verbose
        #![allow(non_camel_case_types)]
        #![allow(non_snake_case)]
        #![no_std]
    });

    out.extend(quote! {
        use core::ops::Deref;
        use core::marker::PhantomData;
    });

    // Retaining the previous assumption
    let mut fpu_present = true;

    if let Some(cpu) = d.cpu.as_ref() {
        let bits = util::unsuffixed(u64::from(cpu.nvic_priority_bits));

        out.extend(quote! {
            ///Number available in the NVIC for configuring priority
            pub const NVIC_PRIO_BITS: u8 = #bits;
        });

        fpu_present = cpu.fpu_present;
    }

    info!(
        "CPU {} FPU",
        if fpu_present { "has" } else { "does not have" }
    );

    out.extend(interrupt::render(&d.peripherals, device_x)?);

    let core_peripherals: &[_] = if fpu_present {
        &[
            "CBP", "CPUID", "DCB", "DWT", "FPB", "FPU", "ITM", "MPU", "NVIC", "SCB", "SYST", "TPIU",
        ]
    } else {
        &[
            "CBP", "CPUID", "DCB", "DWT", "FPB", "ITM", "MPU", "NVIC", "SCB", "SYST", "TPIU",
        ]
    };

    let mut fields = TokenStream::new();
    let mut exprs = TokenStream::new();

    out.extend(quote! {
        pub use cortex_m::peripheral::Peripherals as CorePeripherals;
        #[cfg(feature = "rt")]
        pub use cortex_m_rt::interrupt;
        #[cfg(feature = "rt")]
        pub use self::Interrupt as interrupt;
    });

    if fpu_present {
        out.extend(quote! {
            pub use cortex_m::peripheral::{
                CBP, CPUID, DCB, DWT, FPB, FPU, ITM, MPU, NVIC, SCB, SYST, TPIU,
            };
        });
    } else {
        out.extend(quote! {
            pub use cortex_m::peripheral::{
                CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU,
            };
        });
    }

    let generic_file = std::str::from_utf8(include_bytes!("generic.rs"))?;

    let tokens = syn::parse_file(generic_file)?.into_token_stream();

    out.extend(quote! {
        #[allow(unused_imports)]
        use generic::*;
        ///Common register and bit access and modify traits
        pub mod generic {
            #tokens
        }
    });

    for p in &d.peripherals {
        if core_peripherals.contains(&&*p.name.to_uppercase()) {
            // Core peripherals are handled above
            continue;
        }

        if p.registers
            .as_ref()
            .map(|v| &v[..])
            .unwrap_or(&[])
            .is_empty()
            && p.derived_from.is_none()
        {
            // No register block will be generated so don't put this peripheral
            // in the `Peripherals` struct
            continue;
        }

        let p = p.name.to_sanitized_upper_case();
        let id = Ident::new(&p, Span::call_site());
        fields.extend(quote! {
            #[doc = #p]
            pub #id: #id,
        });
        exprs.extend(quote!(#id: #id { _marker: PhantomData },));
    }

    let span = Span::call_site();

    let take = Some(Ident::new("cortex_m", span)).map(|krate| {
        quote! {
            ///Returns all the peripherals *once*
            #[inline]
            pub fn take() -> Option<Self> {
                #krate::interrupt::free(|_| {
                    if unsafe { DEVICE_PERIPHERALS } {
                        None
                    } else {
                        Some(unsafe { Peripherals::steal() })
                    }
                })
            }
        }
    });

    out.extend(quote! {
        // NOTE `no_mangle` is used here to prevent linking different minor versions of the device
        // crate as that would let you `take` the device peripherals more than once (one per minor
        // version)
        #[no_mangle]
        static mut DEVICE_PERIPHERALS: bool = false;

        ///All the peripherals
        #[allow(non_snake_case)]
        pub struct Peripherals {
            #fields
        }

        impl Peripherals {
            #take

            ///Unchecked version of `Peripherals::take`
            #[inline]
            pub unsafe fn steal() -> Self {
                DEVICE_PERIPHERALS = true;

                Peripherals {
                    #exprs
                }
            }
        }
    });

    Ok(out)
}
